Revert "chore: reapply workflow 5"
This reverts commit 5c1846a18c2d5d1b497c9b4b9d1fc6b467dc7288.

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -6,3 +6,9 @@ PATH="/usr/local/bin:$PATH"
 
 # Perform lint check on files in the staging area through .lintstagedrc configuration
 pnpm exec lint-staged
+
+# 检查暂存区中是否有 -lock.yaml 文件
+if git diff --cached --name-only | grep -q '\pnpm-lock.yaml'; then
+  echo "Error: The pnpm-lock.yaml file cannot be committed!"
+  exit 1
+fi
